# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: docker datastore emulator CI

on:
  pull_request:
    branches: [ "develop", "master" ]

jobs:
  build-docker:
    # create a job that builds application docker image and pushes it to GitHub Container Registry
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --tag ghcr.io/${{ github.repository }}:latest

    - name: Push the Docker image to the Container registry
      run: |
        docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
        docker push ghcr.io/${{ github.repository }}:latest

  